// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sufzofhyzvnqltgcmvwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1ZnpvZmh5enZucWx0Z2NtdndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODEyNzAsImV4cCI6MjA2OTk1NzI3MH0.8yMgRSgxdz2tUXagKZKhgHtBRl7uFbB4_i-L00o1XWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});